services:
  - type: web
    name: wizpay-backend
    env: node
    plan: starter
    buildCommand: npm ci || npm install && npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # GCP Cloud SQL Connection Configuration
      # Using TCP connection for Render (external to GCP)
      - key: INSTANCE_HOST
        value: 34.31.105.133
      - key: DB_HOST
        value: 34.31.105.133
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: rishad
      - key: DB_NAME
        value: wizpay_staging
      - key: DB_PASS
        value: '}9B8dF8i3vb"_65&'
      # Keep for reference (not used with TCP connection)
      # - key: INSTANCE_CONNECTION_NAME
      #   value: best-live-404609:us-central1:wizpay-master
      - key: TIMEZONE
        value: Asia/Kolkata
      # Updated to use same service URL
      - key: ORDER_CREATE_REDIRECT_URL
        value: https://wizpay-backend.onrender.com
      - key: WHITELIST_HOSTS
        value: wizpay-backend.onrender.com
      # JWT Configuration
      - key: JWT_SECRET
        value: test_jwt_secret
      - key: JWT_EXPIRATION
        value: 8h

# No databases section needed - using external GCP Cloud SQL
