services:
  - type: web
    name: wizpay-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: wizpay-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: wizpay-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: wizpay-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: wizpay-db
          property: database
      - key: TIMEZONE
        value: Asia/Kolkata
      - key: ORDER_CREATE_REDIRECT_URL
        value: https://wizpay-frontend.onrender.com

  - type: web
    name: wizpay-frontend
    env: static
    buildCommand: cd front-end && npm install && npm run build
    staticPublishPath: front-end/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: wizpay-db
    databaseName: wizpay_staging
    user: wizpay_user
