services:
  - type: web
    name: wizpay-fullstack
    env: node
    plan: starter
    buildCommand: |
      # Install backend dependencies
      npm install
      # Ensure views directory exists
      mkdir -p views
      # Install frontend dependencies with legacy peer deps and force to resolve conflicts
      cd front-end
      echo "Installing frontend dependencies..."
      npm install --legacy-peer-deps --force || npm install --force || echo "Frontend install failed, continuing with existing build"
      # Try to build frontend directly to views directory (preferred method)
      echo "Building frontend directly to views directory..."
      npm run build-views || npm run build || echo "Frontend build failed, using existing views"
      cd ..
      # If build-views didn't work, try copying from dist
      if [ -d "front-end/dist" ] && [ "$(ls -A front-end/dist 2>/dev/null)" ]; then
        echo "Copying from dist to views..."
        cp -r front-end/dist/* views/ 2>/dev/null || echo "Copy from dist failed"
      fi
      # Verify views directory has content
      echo "Final views directory contents:"
      ls -la views/ || echo "Views directory check failed"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # GCP Cloud SQL Connection Configuration
      # Using TCP connection for Render (external to GCP)
      - key: INSTANCE_HOST
        value: 34.31.105.133
      - key: DB_HOST
        value: 34.31.105.133
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: rishad
      - key: DB_NAME
        value: wizpay_staging
      - key: DB_PASS
        value: '}9B8dF8i3vb"_65&'
      # Keep for reference (not used with TCP connection)
      # - key: INSTANCE_CONNECTION_NAME
      #   value: best-live-404609:us-central1:wizpay-master
      - key: TIMEZONE
        value: Asia/Kolkata
      # Updated to use same service URL
      - key: ORDER_CREATE_REDIRECT_URL
        value: https://wizpay-fullstack.onrender.com
      # JWT Configuration
      - key: JWT_SECRET
        value: test_jwt_secret
      - key: JWT_EXPIRATION
        value: 8h

# No databases section needed - using external GCP Cloud SQL
