services:
  - type: web
    name: wizpay-backend
    env: node
    plan: starter
    buildCommand: npm run render-build || (npm ci || npm install && npm run render-build)
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # GCP Cloud SQL Connection Configuration (TCP)
      - key: INSTANCE_HOST
        value: 34.31.105.133
      - key: DB_HOST
        value: 34.31.105.133
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: rishad
      - key: DB_NAME
        value: wizpay_staging
      - key: TIMEZONE
        value: Asia/Kolkata
      # Using same service URL for redirects and whitelisting
      - key: ORDER_CREATE_REDIRECT_URL
        value: https://wizpay-backend.onrender.com
      - key: WHITELIST_HOSTS
        value: wizpay-backend.onrender.com
      # JWT Configuration
      - key: JWT_SECRET
        value: test_jwt_secret
      - key: JWT_EXPIRATION
        value: 8h
