// write middleware to check if user is admin.
// req.user will already be generated by previous middleware with req.user.role = 'admin' or 'user'
const db = require("../../db");

async function isAdmin(req, res, next) {
  if (req.user.role === "admin") {
    next();
  } else {
    if (req.originalUrl == "/api/v1/reports") {
      if (req.user.role === "subadmin") {
        next();
      } else {
        return res.status(401).json({
          success: false,
          message: "Unauthorized: You are not an sub admin.",
        });
      }
    } else {
      return res.status(401).json({
        success: false,
        message: "Unauthorized: You are not an admin.",
      });
    }
  }
}

module.exports = isAdmin;
