// write middleware to check if user is admin.
// req.user will already be generated by previous middleware with req.user.role = 'admin' or 'user'
const db = require("../../db");

async function isSuperAdmin(req, res, next) {
  if (req.user.role === "superadmin") {
    next();
  } else {
    return res.status(401).json({
      success: false,
      message: "Unauthorized: You are not a super admin.",
    });
  }
}

module.exports = isSuperAdmin;
